/**
 * Every URL in the sitemap must be indexable. Nothing else may be.
 *
 *   npm run test:integration
 *
 * ─────────────────────────────────────────────────────────────────────────────────────
 * THE DEFECT THIS EXISTS TO CATCH.
 *
 * sitemap.xml is generated at RUNTIME from the services table. Prerendering runs at BUILD
 * time with no database. So the 17 /service/:slug URLs — plus, as it turned out, the three
 * legal pages and /ppf-ceramic-coating — appeared in the sitemap with no prerendered file,
 * fell through to the SPA catch-all, and were served 404.html: "Page not found", with
 * `robots: noindex, follow`.
 *
 * React then rendered the real page for humans and useSeoMeta fixed the title, but
 * useSeoMeta does not manage the robots tag, so the noindex survived hydration. 21 URLs
 * were being submitted for indexing while each one told Google not to index it. Nothing
 * failed, nothing logged, and the only symptom was rankings.
 *
 * The two halves of this file are deliberately different in kind:
 *
 *   structural   runs always. Asserts the ROUTE PIPELINE cannot reintroduce the gap.
 *   served       runs against the real built output over real HTTP, with the real
 *                serveStatic and the real sitemap handler. Needs `npm run build` first.
 * ─────────────────────────────────────────────────────────────────────────────────────
 */
import { test, describe, before, after, mock } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express from "express";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST = path.join(repoRoot, "dist", "public");
const built = fs.existsSync(path.join(DIST, "index.html"));

/** The live catalogue's slugs, so the mocked database matches production. */
const SERVICE_SLUGS = [
  "1-year-bike-ceramic-coating", "1-year-ceramic-coating", "annual-maintenance-package",
  "car-polishing", "exterior-detailing-hard-water-new", "headlight-restoration-both",
  "interior-detailing-service", "partial-ppf-hatchback", "partial-ppf-sedan",
  "partial-ppf-suv", "ppf-hatchback", "ppf-sedan", "ppf-suv", "stek-suncontrol-films",
  "stek-windsheild-suncontrol-films", "windshield-glass-coating-new", "windshield-glass-polishing",
];

const services = SERVICE_SLUGS.map((slug, i) => ({
  id: "svc-" + i, slug,
  title: slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
  description: `Professional ${slug.replace(/-/g, " ")} at P91 Car Care in Indiranagar, Bangalore.`,
  metaTitle: null, metaDescription: null,
  price: "2999.00", originalPrice: "5999.00", duration: 120,
  images: [`/attached_assets/services/${slug}.webp`],
  isActive: true, maxBookingsPerSlot: 3,
}));

// ===========================================================================
// STRUCTURAL — always runs, no build required
// ===========================================================================
describe("route pipeline: nothing in the sitemap may be left without a handler", () => {
  const read = (p) => fs.readFileSync(path.join(repoRoot, p), "utf8");
  const routesSrc = read("server/routes.ts");
  const prerenderSrc = read("scripts/prerender.mjs");
  const viteSrc = read("server/vite.ts");

  /** The literal `loc:` paths the sitemap handler emits. */
  const sitemapStaticPaths = [...routesSrc.matchAll(/\{\s*loc:\s*"([^"]+)"/g)].map((m) => m[1]);

  /** Paths prerendered from the STATIC_ROUTES table. */
  const staticRouteTable = prerenderSrc.slice(
    prerenderSrc.indexOf("const STATIC_ROUTES"),
    prerenderSrc.indexOf("/** Bundle the TS"),
  );
  const prerenderedStatic = [...staticRouteTable.matchAll(/path:\s*"([^"]+)"/g)].map((m) => m[1]);

  test("the sitemap emits the paths we expect", () => {
    assert.ok(sitemapStaticPaths.includes("/"), "homepage");
    assert.ok(sitemapStaticPaths.length >= 12, `expected the full static list, got ${sitemapStaticPaths.length}`);
  });

  test("EVERY static sitemap path is prerendered or generated from a content module", () => {
    // Blog posts, SEO pages and the campaign landing pages are generated by iterating
    // their content modules (BLOG_POSTS, SEO_PAGES, LANDING_PAGES), so they reach the
    // prerender output without a literal entry in STATIC_ROUTES.
    const generatedPrefixes = ["/blog", "/services/"];
    const landingPaths = prerenderSrc.includes("of LANDING_PAGES")
      ? ["/ceramic-coating/car", "/ceramic-coating/bike", "/ppf"]
      : [];
    const missing = sitemapStaticPaths.filter(
      (p) =>
        !prerenderedStatic.includes(p) &&
        !landingPaths.includes(p) &&
        !generatedPrefixes.some((g) => p.startsWith(g)),
    );
    assert.deepEqual(
      missing, [],
      `these sitemap URLs have no prerendered file, so serveStatic serves them 404.html ` +
      `with noindex while the sitemap asks Google to index them: ${missing.join(", ")}`,
    );
  });

  test("the three legal pages and /ppf-ceramic-coating are prerendered", () => {
    // The exact four that were broken. Named individually so a regression says which.
    for (const p of ["/privacy-policy", "/terms-conditions", "/refund-policy", "/ppf-ceramic-coating"]) {
      assert.ok(prerenderedStatic.includes(p), `${p} must be prerendered`);
    }
  });

  test("/service/:slug has a dedicated server handler, since the build has no database", () => {
    assert.match(viteSrc, /app\.get\("\/service\/:slug"/, "the route must exist");
    assert.match(viteSrc, /app\.html/, "it must serve the indexable shell");
    assert.match(viteSrc, /getServiceBySlug/, "it must validate the slug against the catalogue");
    assert.match(viteSrc, /if \(!service \|\| !service\.isActive\) return next\(\)/,
      "an unknown or retired slug must fall through to the real 404");
  });

  test("the indexable shell carries no title and no robots directive", () => {
    assert.match(prerenderSrc, /app shell must not carry a title/);
    assert.match(prerenderSrc, /app shell must not carry a robots directive/);
  });

  test("404.html keeps its noindex — removing it would be a worse defect", () => {
    assert.match(prerenderSrc, /noindex, follow/);
    assert.match(prerenderSrc, /404 shell lost its noindex/);
  });
});

// ===========================================================================
// SERVED — real HTTP against the real built output
// ===========================================================================
describe("served HTML: every sitemap URL is indexable, and only those", { skip: !built ? "run `npm run build` first" : false }, () => {
  let server, base;

  before(async () => {
    const storage = {
      getAllServices: async () => services,
      getServiceBySlug: async (slug) => services.find((s) => s.slug === slug),
      getService: async (id) => services.find((s) => s.id === id),
      getSetting: async () => undefined,
      getAllCampaigns: async () => [],
      getAllBlackoutDates: async () => [],
      getBusinessHoursForDay: async () => undefined,
      getAllBusinessHours: async () => [],
      getBookingCountForSlot: async () => 0,
      getBooking: async () => undefined,
      getBookingByConfirmationToken: async () => undefined,
      getBookingByPaymentOrderId: async () => undefined,
      getBookingsByStatus: async () => [],
      getTimeSlot: async () => undefined,
      getAllPpfLeads: async () => [],
      getAdmin: async () => undefined,
    };
    class SlotFullError extends Error {}
    mock.module("../server/storage.ts", { exports: { storage, SlotFullError } });
    mock.module("../server/services/scheduler.ts", { exports: { schedulerService: { startReminderScheduler() {} } } });

    process.env.DATABASE_URL = "postgresql://u:p@127.0.0.1:5432/none";
    process.env.SESSION_SECRET = "sitemap-test-secret";
    process.env.NODE_ENV = "test";
    process.env.PUBLIC_SITE_ORIGIN = "https://p91carcare.com";

    const { registerRoutes } = await import("../server/routes.ts");
    const { serveStatic } = await import("../server/vite.ts");
    const app = express();
    app.use(express.json());
    server = await registerRoutes(app);
    serveStatic(app, DIST);
    await new Promise((r) => server.listen(0, "127.0.0.1", r));
    base = `http://127.0.0.1:${server.address().port}`;
  });

  after(async () => { if (server) await new Promise((r) => server.close(r)); });

  const get = async (p) => {
    const res = await fetch(base + p);
    return { status: res.status, html: await res.text() };
  };
  const isNoindex = (html) => /name="robots"[^>]*noindex/i.test(html);
  const isNotFound = (html) => /<title>Page not found/i.test(html);

  test("every URL in the sitemap returns indexable HTML", async () => {
    const sitemap = await get("/sitemap.xml");
    assert.equal(sitemap.status, 200);
    const urls = [...sitemap.html.matchAll(/<loc>([^<]+)<\/loc>/g)]
      .map((m) => m[1].replace("https://p91carcare.com", ""));

    assert.ok(urls.length >= 30, `expected the full sitemap, got ${urls.length}`);

    const broken = [];
    for (const url of urls) {
      const r = await get(url);
      if (r.status !== 200) { broken.push(`${url} -> HTTP ${r.status}`); continue; }
      if (isNoindex(r.html)) { broken.push(`${url} -> noindex`); continue; }
      if (isNotFound(r.html)) { broken.push(`${url} -> "Page not found" shell`); continue; }
      if (!/<title>[^<]{10,}<\/title>/.test(r.html)) broken.push(`${url} -> no meaningful title`);
    }

    assert.deepEqual(
      broken, [],
      "these sitemap URLs are not indexable — the sitemap asks Google to index them " +
      "while the page tells it not to:\n  " + broken.join("\n  "),
    );
  });

  test("each /service/:slug carries its own title, canonical and Service schema", async () => {
    for (const slug of ["1-year-ceramic-coating", "ppf-suv", "windshield-glass-polishing"]) {
      const r = await get(`/service/${slug}`);
      assert.equal(r.status, 200, slug);
      assert.ok(!isNoindex(r.html), `${slug} must not be noindex`);
      assert.ok(!isNotFound(r.html), `${slug} must not be the 404 shell`);
      assert.match(r.html, new RegExp(`<link rel="canonical" href="https://p91carcare\\.com/service/${slug}"`), slug);
      assert.match(r.html, /"@type":"Service"/, `${slug} needs Service schema`);
      assert.match(r.html, /<meta property="og:title"/, slug);
      // Exactly one of each — the prerender shell must not also be contributing one.
      assert.equal((r.html.match(/<title>/g) || []).length, 1, `${slug}: one title`);
      assert.equal((r.html.match(/<link rel="canonical"/g) || []).length, 1, `${slug}: one canonical`);
      assert.equal((r.html.match(/<meta property="og:title"/g) || []).length, 1, `${slug}: one og:title`);
    }
  });

  test("the service page price in schema comes from the record, not a literal", async () => {
    const r = await get("/service/ppf-suv");
    assert.match(r.html, /"price":"2999\.00"/, "the mocked record's price, proving it is read from storage");
  });

  test("an INVALID service slug still returns the noindex 404 shell", async () => {
    // The distinction that matters: fixing the valid routes must not make junk indexable.
    for (const bad of ["/service/does-not-exist", "/service/../etc", "/service/ppf-suvXXX"]) {
      const r = await get(bad);
      assert.ok(isNoindex(r.html), `${bad} must stay noindex`);
      assert.ok(isNotFound(r.html), `${bad} must render the not-found shell`);
    }
  });

  test("an entirely unknown route still returns the noindex 404 shell", async () => {
    for (const bad of ["/nonsense", "/blog/no-such-post", "/services/no-such-page"]) {
      const r = await get(bad);
      assert.ok(isNoindex(r.html), `${bad} must stay noindex`);
    }
  });

  test("the three campaign landing pages are indexable and carry their own metadata", async () => {
    for (const [url, needle] of [
      ["/ceramic-coating/car", /Car Ceramic Coating Price in Bangalore/],
      ["/ceramic-coating/bike", /Bike Ceramic Coating in Bangalore/],
      ["/ppf", /Car PPF Price in Bangalore/],
    ]) {
      const r = await get(url);
      assert.ok(!isNoindex(r.html), `${url} must not be noindex`);
      assert.match(r.html, needle, `${url} must carry its own title`);
    }
  });
});
